#name, main, version and api are required
name: GotifyNotifications
main: kdurrance\GotifyNotifications\MainClass
version: 0.0.9
api: 3.0.0

load: POSTWORLD
author: Karl Durrance
description: Post Pocketmine notifications to a Gotify server
website: https://github.com/kdurrance/GotifyNotifications
